// Gantry coordination RPCs (libp2p, length-prefixed protobuf).
//
// Carried over libp2p stream protocol ID `/gantry/coord/1.0.0` as described in
// detailed-design.md §4.4. One stream per request/response pair; the stream
// is closed after the response is written. Forward-compat policy: additive
// changes bump the minor (`/gantry/coord/1.1.0`), breaking changes bump the
// major (`/gantry/coord/2.0.0`).
//
// gRPC is intentionally avoided — `go-msgio` length-delimited framing is
// sufficient and avoids HTTP-over-libp2p complexity.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gantry/coord/v1/coord.proto

package coordv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FailureClass classifies the cause of a terminal origin pull failure.
// See detailed-design.md §5.8 for semantics and cluster-wide trust rules.
type FailureClass int32

const (
	FailureClass_FAILURE_CLASS_UNSPECIFIED  FailureClass = 0
	FailureClass_FAILURE_CLASS_AUTH         FailureClass = 1 // 401 / 403 from origin
	FailureClass_FAILURE_CLASS_NOT_FOUND    FailureClass = 2 // 404 from origin
	FailureClass_FAILURE_CLASS_RATE_LIMITED FailureClass = 3 // 429 from origin
	FailureClass_FAILURE_CLASS_TRANSIENT    FailureClass = 4 // connection / timeout / DNS / 5xx
)

// Enum value maps for FailureClass.
var (
	FailureClass_name = map[int32]string{
		0: "FAILURE_CLASS_UNSPECIFIED",
		1: "FAILURE_CLASS_AUTH",
		2: "FAILURE_CLASS_NOT_FOUND",
		3: "FAILURE_CLASS_RATE_LIMITED",
		4: "FAILURE_CLASS_TRANSIENT",
	}
	FailureClass_value = map[string]int32{
		"FAILURE_CLASS_UNSPECIFIED":  0,
		"FAILURE_CLASS_AUTH":         1,
		"FAILURE_CLASS_NOT_FOUND":    2,
		"FAILURE_CLASS_RATE_LIMITED": 3,
		"FAILURE_CLASS_TRANSIENT":    4,
	}
)

func (x FailureClass) Enum() *FailureClass {
	p := new(FailureClass)
	*p = x
	return p
}

func (x FailureClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureClass) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_coord_v1_coord_proto_enumTypes[0].Descriptor()
}

func (FailureClass) Type() protoreflect.EnumType {
	return &file_gantry_coord_v1_coord_proto_enumTypes[0]
}

func (x FailureClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureClass.Descriptor instead.
func (FailureClass) EnumDescriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{0}
}

// Kind discriminates the OCI Distribution Spec URL family the puller
// should target at the upstream registry:
//
//	/v2/<repo>/blobs/<digest>      (KIND_BLOB)
//	/v2/<repo>/manifests/<digest>  (KIND_MANIFEST)
//
// KIND_UNSPECIFIED is treated as KIND_BLOB for back-compat with peers
// running pre-Kind builds.
type PleasePullRequest_Kind int32

const (
	PleasePullRequest_KIND_UNSPECIFIED PleasePullRequest_Kind = 0
	PleasePullRequest_KIND_BLOB        PleasePullRequest_Kind = 1
	PleasePullRequest_KIND_MANIFEST    PleasePullRequest_Kind = 2
)

// Enum value maps for PleasePullRequest_Kind.
var (
	PleasePullRequest_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_BLOB",
		2: "KIND_MANIFEST",
	}
	PleasePullRequest_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED": 0,
		"KIND_BLOB":        1,
		"KIND_MANIFEST":    2,
	}
)

func (x PleasePullRequest_Kind) Enum() *PleasePullRequest_Kind {
	p := new(PleasePullRequest_Kind)
	*p = x
	return p
}

func (x PleasePullRequest_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PleasePullRequest_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_coord_v1_coord_proto_enumTypes[1].Descriptor()
}

func (PleasePullRequest_Kind) Type() protoreflect.EnumType {
	return &file_gantry_coord_v1_coord_proto_enumTypes[1]
}

func (x PleasePullRequest_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PleasePullRequest_Kind.Descriptor instead.
func (PleasePullRequest_Kind) EnumDescriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{3, 0}
}

type PleasePullResponse_Result_Outcome int32

const (
	PleasePullResponse_Result_OUTCOME_UNSPECIFIED     PleasePullResponse_Result_Outcome = 0
	PleasePullResponse_Result_OUTCOME_ALREADY_PULLING PleasePullResponse_Result_Outcome = 1
	PleasePullResponse_Result_OUTCOME_STARTED         PleasePullResponse_Result_Outcome = 2
	PleasePullResponse_Result_OUTCOME_RECENTLY_FAILED PleasePullResponse_Result_Outcome = 3
)

// Enum value maps for PleasePullResponse_Result_Outcome.
var (
	PleasePullResponse_Result_Outcome_name = map[int32]string{
		0: "OUTCOME_UNSPECIFIED",
		1: "OUTCOME_ALREADY_PULLING",
		2: "OUTCOME_STARTED",
		3: "OUTCOME_RECENTLY_FAILED",
	}
	PleasePullResponse_Result_Outcome_value = map[string]int32{
		"OUTCOME_UNSPECIFIED":     0,
		"OUTCOME_ALREADY_PULLING": 1,
		"OUTCOME_STARTED":         2,
		"OUTCOME_RECENTLY_FAILED": 3,
	}
)

func (x PleasePullResponse_Result_Outcome) Enum() *PleasePullResponse_Result_Outcome {
	p := new(PleasePullResponse_Result_Outcome)
	*p = x
	return p
}

func (x PleasePullResponse_Result_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PleasePullResponse_Result_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_gantry_coord_v1_coord_proto_enumTypes[2].Descriptor()
}

func (PleasePullResponse_Result_Outcome) Type() protoreflect.EnumType {
	return &file_gantry_coord_v1_coord_proto_enumTypes[2]
}

func (x PleasePullResponse_Result_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PleasePullResponse_Result_Outcome.Descriptor instead.
func (PleasePullResponse_Result_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{4, 0, 0}
}

// Envelope is the single message kind sent over `/gantry/coord/1.0.0`.
// Receivers dispatch on the `msg` oneof.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Envelope_PullIntentRequest
	//	*Envelope_PullIntentResponse
	//	*Envelope_PleasePullRequest
	//	*Envelope_PleasePullResponse
	Msg           isEnvelope_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMsg() isEnvelope_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Envelope) GetPullIntentRequest() *PullIntentRequest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_PullIntentRequest); ok {
			return x.PullIntentRequest
		}
	}
	return nil
}

func (x *Envelope) GetPullIntentResponse() *PullIntentResponse {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_PullIntentResponse); ok {
			return x.PullIntentResponse
		}
	}
	return nil
}

func (x *Envelope) GetPleasePullRequest() *PleasePullRequest {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_PleasePullRequest); ok {
			return x.PleasePullRequest
		}
	}
	return nil
}

func (x *Envelope) GetPleasePullResponse() *PleasePullResponse {
	if x != nil {
		if x, ok := x.Msg.(*Envelope_PleasePullResponse); ok {
			return x.PleasePullResponse
		}
	}
	return nil
}

type isEnvelope_Msg interface {
	isEnvelope_Msg()
}

type Envelope_PullIntentRequest struct {
	PullIntentRequest *PullIntentRequest `protobuf:"bytes,1,opt,name=pull_intent_request,json=pullIntentRequest,proto3,oneof"`
}

type Envelope_PullIntentResponse struct {
	PullIntentResponse *PullIntentResponse `protobuf:"bytes,2,opt,name=pull_intent_response,json=pullIntentResponse,proto3,oneof"`
}

type Envelope_PleasePullRequest struct {
	PleasePullRequest *PleasePullRequest `protobuf:"bytes,3,opt,name=please_pull_request,json=pleasePullRequest,proto3,oneof"`
}

type Envelope_PleasePullResponse struct {
	PleasePullResponse *PleasePullResponse `protobuf:"bytes,4,opt,name=please_pull_response,json=pleasePullResponse,proto3,oneof"`
}

func (*Envelope_PullIntentRequest) isEnvelope_Msg() {}

func (*Envelope_PullIntentResponse) isEnvelope_Msg() {}

func (*Envelope_PleasePullRequest) isEnvelope_Msg() {}

func (*Envelope_PleasePullResponse) isEnvelope_Msg() {}

// PullIntentRequest asks a peer whether it has a digest cached, is currently
// pulling it, or has recently failed to pull it. See §5.2 step 4.
type PullIntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        string                 `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"` // OCI digest, e.g. "sha256:abc..."
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullIntentRequest) Reset() {
	*x = PullIntentRequest{}
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullIntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullIntentRequest) ProtoMessage() {}

func (x *PullIntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullIntentRequest.ProtoReflect.Descriptor instead.
func (*PullIntentRequest) Descriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{1}
}

func (x *PullIntentRequest) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

// PullIntentResponse carries the recipient's authoritative state for the
// queried digest. See §5.2 step 5 for how requesters evaluate the response.
type PullIntentResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	HasCached bool                   `protobuf:"varint,1,opt,name=has_cached,json=hasCached,proto3" json:"has_cached,omitempty"`
	InFlight  bool                   `protobuf:"varint,2,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	StartedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	// Recipient's own rank in recipient's view; requester compares against its
	// own rank computation to detect informer divergence (§5.3) and emit
	// `p2p_hrw_rank_mismatch_total`.
	HrwRank int32 `protobuf:"varint,4,opt,name=hrw_rank,json=hrwRank,proto3" json:"hrw_rank,omitempty"`
	// §5.8 origin-failure circuit-breaker state. Meaningful only when
	// recently_failed is true.
	RecentlyFailed bool                   `protobuf:"varint,5,opt,name=recently_failed,json=recentlyFailed,proto3" json:"recently_failed,omitempty"`
	CooldownUntil  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=cooldown_until,json=cooldownUntil,proto3" json:"cooldown_until,omitempty"`
	FailureClass   FailureClass           `protobuf:"varint,7,opt,name=failure_class,json=failureClass,proto3,enum=gantry.coord.v1.FailureClass" json:"failure_class,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PullIntentResponse) Reset() {
	*x = PullIntentResponse{}
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullIntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullIntentResponse) ProtoMessage() {}

func (x *PullIntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullIntentResponse.ProtoReflect.Descriptor instead.
func (*PullIntentResponse) Descriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{2}
}

func (x *PullIntentResponse) GetHasCached() bool {
	if x != nil {
		return x.HasCached
	}
	return false
}

func (x *PullIntentResponse) GetInFlight() bool {
	if x != nil {
		return x.InFlight
	}
	return false
}

func (x *PullIntentResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PullIntentResponse) GetHrwRank() int32 {
	if x != nil {
		return x.HrwRank
	}
	return 0
}

func (x *PullIntentResponse) GetRecentlyFailed() bool {
	if x != nil {
		return x.RecentlyFailed
	}
	return false
}

func (x *PullIntentResponse) GetCooldownUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.CooldownUntil
	}
	return nil
}

func (x *PullIntentResponse) GetFailureClass() FailureClass {
	if x != nil {
		return x.FailureClass
	}
	return FailureClass_FAILURE_CLASS_UNSPECIFIED
}

// PleasePullRequest asks a peer to pull the named digests from origin on the
// sender's behalf. See §5.2 step 6 and §5.2a for batching rules.
type PleasePullRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Batched (§5.2a). All digests in a single batch MUST share
	// `upstream_registry`, `repository`, AND `kind`. Mixed-kind batches
	// require separate calls.
	Digests          []string               `protobuf:"bytes,1,rep,name=digests,proto3" json:"digests,omitempty"`
	UpstreamRegistry string                 `protobuf:"bytes,2,opt,name=upstream_registry,json=upstreamRegistry,proto3" json:"upstream_registry,omitempty"` // e.g. "registry.example.com"
	Repository       string                 `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`                                     // e.g. "library/nginx"
	Kind             PleasePullRequest_Kind `protobuf:"varint,4,opt,name=kind,proto3,enum=gantry.coord.v1.PleasePullRequest_Kind" json:"kind,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PleasePullRequest) Reset() {
	*x = PleasePullRequest{}
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleasePullRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleasePullRequest) ProtoMessage() {}

func (x *PleasePullRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleasePullRequest.ProtoReflect.Descriptor instead.
func (*PleasePullRequest) Descriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{3}
}

func (x *PleasePullRequest) GetDigests() []string {
	if x != nil {
		return x.Digests
	}
	return nil
}

func (x *PleasePullRequest) GetUpstreamRegistry() string {
	if x != nil {
		return x.UpstreamRegistry
	}
	return ""
}

func (x *PleasePullRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *PleasePullRequest) GetKind() PleasePullRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return PleasePullRequest_KIND_UNSPECIFIED
}

// PleasePullResponse reports the per-digest outcome of a `please_pull` request.
type PleasePullResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Results       []*PleasePullResponse_Result `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PleasePullResponse) Reset() {
	*x = PleasePullResponse{}
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleasePullResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleasePullResponse) ProtoMessage() {}

func (x *PleasePullResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleasePullResponse.ProtoReflect.Descriptor instead.
func (*PleasePullResponse) Descriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{4}
}

func (x *PleasePullResponse) GetResults() []*PleasePullResponse_Result {
	if x != nil {
		return x.Results
	}
	return nil
}

type PleasePullResponse_Result struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Digest        string                            `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	Outcome       PleasePullResponse_Result_Outcome `protobuf:"varint,2,opt,name=outcome,proto3,enum=gantry.coord.v1.PleasePullResponse_Result_Outcome" json:"outcome,omitempty"`
	StartedAt     *timestamppb.Timestamp            `protobuf:"bytes,3,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CooldownUntil *timestamppb.Timestamp            `protobuf:"bytes,4,opt,name=cooldown_until,json=cooldownUntil,proto3" json:"cooldown_until,omitempty"`
	FailureClass  FailureClass                      `protobuf:"varint,5,opt,name=failure_class,json=failureClass,proto3,enum=gantry.coord.v1.FailureClass" json:"failure_class,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PleasePullResponse_Result) Reset() {
	*x = PleasePullResponse_Result{}
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PleasePullResponse_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PleasePullResponse_Result) ProtoMessage() {}

func (x *PleasePullResponse_Result) ProtoReflect() protoreflect.Message {
	mi := &file_gantry_coord_v1_coord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PleasePullResponse_Result.ProtoReflect.Descriptor instead.
func (*PleasePullResponse_Result) Descriptor() ([]byte, []int) {
	return file_gantry_coord_v1_coord_proto_rawDescGZIP(), []int{4, 0}
}

func (x *PleasePullResponse_Result) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *PleasePullResponse_Result) GetOutcome() PleasePullResponse_Result_Outcome {
	if x != nil {
		return x.Outcome
	}
	return PleasePullResponse_Result_OUTCOME_UNSPECIFIED
}

func (x *PleasePullResponse_Result) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *PleasePullResponse_Result) GetCooldownUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.CooldownUntil
	}
	return nil
}

func (x *PleasePullResponse_Result) GetFailureClass() FailureClass {
	if x != nil {
		return x.FailureClass
	}
	return FailureClass_FAILURE_CLASS_UNSPECIFIED
}

var File_gantry_coord_v1_coord_proto protoreflect.FileDescriptor

const file_gantry_coord_v1_coord_proto_rawDesc = "" +
	"\n" +
	"\x1bgantry/coord/v1/coord.proto\x12\x0fgantry.coord.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x02\n" +
	"\bEnvelope\x12T\n" +
	"\x13pull_intent_request\x18\x01 \x01(\v2\".gantry.coord.v1.PullIntentRequestH\x00R\x11pullIntentRequest\x12W\n" +
	"\x14pull_intent_response\x18\x02 \x01(\v2#.gantry.coord.v1.PullIntentResponseH\x00R\x12pullIntentResponse\x12T\n" +
	"\x13please_pull_request\x18\x03 \x01(\v2\".gantry.coord.v1.PleasePullRequestH\x00R\x11pleasePullRequest\x12W\n" +
	"\x14please_pull_response\x18\x04 \x01(\v2#.gantry.coord.v1.PleasePullResponseH\x00R\x12pleasePullResponseB\x05\n" +
	"\x03msg\"+\n" +
	"\x11PullIntentRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\"\xd6\x02\n" +
	"\x12PullIntentResponse\x12\x1d\n" +
	"\n" +
	"has_cached\x18\x01 \x01(\bR\thasCached\x12\x1b\n" +
	"\tin_flight\x18\x02 \x01(\bR\binFlight\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12\x19\n" +
	"\bhrw_rank\x18\x04 \x01(\x05R\ahrwRank\x12'\n" +
	"\x0frecently_failed\x18\x05 \x01(\bR\x0erecentlyFailed\x12A\n" +
	"\x0ecooldown_until\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rcooldownUntil\x12B\n" +
	"\rfailure_class\x18\a \x01(\x0e2\x1d.gantry.coord.v1.FailureClassR\ffailureClass\"\xf7\x01\n" +
	"\x11PleasePullRequest\x12\x18\n" +
	"\adigests\x18\x01 \x03(\tR\adigests\x12+\n" +
	"\x11upstream_registry\x18\x02 \x01(\tR\x10upstreamRegistry\x12\x1e\n" +
	"\n" +
	"repository\x18\x03 \x01(\tR\n" +
	"repository\x12;\n" +
	"\x04kind\x18\x04 \x01(\x0e2'.gantry.coord.v1.PleasePullRequest.KindR\x04kind\">\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tKIND_BLOB\x10\x01\x12\x11\n" +
	"\rKIND_MANIFEST\x10\x02\"\x86\x04\n" +
	"\x12PleasePullResponse\x12D\n" +
	"\aresults\x18\x01 \x03(\v2*.gantry.coord.v1.PleasePullResponse.ResultR\aresults\x1a\xa9\x03\n" +
	"\x06Result\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\tR\x06digest\x12L\n" +
	"\aoutcome\x18\x02 \x01(\x0e22.gantry.coord.v1.PleasePullResponse.Result.OutcomeR\aoutcome\x129\n" +
	"\n" +
	"started_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12A\n" +
	"\x0ecooldown_until\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\rcooldownUntil\x12B\n" +
	"\rfailure_class\x18\x05 \x01(\x0e2\x1d.gantry.coord.v1.FailureClassR\ffailureClass\"w\n" +
	"\aOutcome\x12\x17\n" +
	"\x13OUTCOME_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17OUTCOME_ALREADY_PULLING\x10\x01\x12\x13\n" +
	"\x0fOUTCOME_STARTED\x10\x02\x12\x1b\n" +
	"\x17OUTCOME_RECENTLY_FAILED\x10\x03\"\x04\b\x04\x10\x04*\x9f\x01\n" +
	"\fFailureClass\x12\x1d\n" +
	"\x19FAILURE_CLASS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12FAILURE_CLASS_AUTH\x10\x01\x12\x1b\n" +
	"\x17FAILURE_CLASS_NOT_FOUND\x10\x02\x12\x1e\n" +
	"\x1aFAILURE_CLASS_RATE_LIMITED\x10\x03\x12\x1b\n" +
	"\x17FAILURE_CLASS_TRANSIENT\x10\x04B8Z6github.com/gantry/gantry/proto/gantry/coord/v1;coordv1b\x06proto3"

var (
	file_gantry_coord_v1_coord_proto_rawDescOnce sync.Once
	file_gantry_coord_v1_coord_proto_rawDescData []byte
)

func file_gantry_coord_v1_coord_proto_rawDescGZIP() []byte {
	file_gantry_coord_v1_coord_proto_rawDescOnce.Do(func() {
		file_gantry_coord_v1_coord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gantry_coord_v1_coord_proto_rawDesc), len(file_gantry_coord_v1_coord_proto_rawDesc)))
	})
	return file_gantry_coord_v1_coord_proto_rawDescData
}

var file_gantry_coord_v1_coord_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_gantry_coord_v1_coord_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_gantry_coord_v1_coord_proto_goTypes = []any{
	(FailureClass)(0),                      // 0: gantry.coord.v1.FailureClass
	(PleasePullRequest_Kind)(0),            // 1: gantry.coord.v1.PleasePullRequest.Kind
	(PleasePullResponse_Result_Outcome)(0), // 2: gantry.coord.v1.PleasePullResponse.Result.Outcome
	(*Envelope)(nil),                       // 3: gantry.coord.v1.Envelope
	(*PullIntentRequest)(nil),              // 4: gantry.coord.v1.PullIntentRequest
	(*PullIntentResponse)(nil),             // 5: gantry.coord.v1.PullIntentResponse
	(*PleasePullRequest)(nil),              // 6: gantry.coord.v1.PleasePullRequest
	(*PleasePullResponse)(nil),             // 7: gantry.coord.v1.PleasePullResponse
	(*PleasePullResponse_Result)(nil),      // 8: gantry.coord.v1.PleasePullResponse.Result
	(*timestamppb.Timestamp)(nil),          // 9: google.protobuf.Timestamp
}
var file_gantry_coord_v1_coord_proto_depIdxs = []int32{
	4,  // 0: gantry.coord.v1.Envelope.pull_intent_request:type_name -> gantry.coord.v1.PullIntentRequest
	5,  // 1: gantry.coord.v1.Envelope.pull_intent_response:type_name -> gantry.coord.v1.PullIntentResponse
	6,  // 2: gantry.coord.v1.Envelope.please_pull_request:type_name -> gantry.coord.v1.PleasePullRequest
	7,  // 3: gantry.coord.v1.Envelope.please_pull_response:type_name -> gantry.coord.v1.PleasePullResponse
	9,  // 4: gantry.coord.v1.PullIntentResponse.started_at:type_name -> google.protobuf.Timestamp
	9,  // 5: gantry.coord.v1.PullIntentResponse.cooldown_until:type_name -> google.protobuf.Timestamp
	0,  // 6: gantry.coord.v1.PullIntentResponse.failure_class:type_name -> gantry.coord.v1.FailureClass
	1,  // 7: gantry.coord.v1.PleasePullRequest.kind:type_name -> gantry.coord.v1.PleasePullRequest.Kind
	8,  // 8: gantry.coord.v1.PleasePullResponse.results:type_name -> gantry.coord.v1.PleasePullResponse.Result
	2,  // 9: gantry.coord.v1.PleasePullResponse.Result.outcome:type_name -> gantry.coord.v1.PleasePullResponse.Result.Outcome
	9,  // 10: gantry.coord.v1.PleasePullResponse.Result.started_at:type_name -> google.protobuf.Timestamp
	9,  // 11: gantry.coord.v1.PleasePullResponse.Result.cooldown_until:type_name -> google.protobuf.Timestamp
	0,  // 12: gantry.coord.v1.PleasePullResponse.Result.failure_class:type_name -> gantry.coord.v1.FailureClass
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_gantry_coord_v1_coord_proto_init() }
func file_gantry_coord_v1_coord_proto_init() {
	if File_gantry_coord_v1_coord_proto != nil {
		return
	}
	file_gantry_coord_v1_coord_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_PullIntentRequest)(nil),
		(*Envelope_PullIntentResponse)(nil),
		(*Envelope_PleasePullRequest)(nil),
		(*Envelope_PleasePullResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gantry_coord_v1_coord_proto_rawDesc), len(file_gantry_coord_v1_coord_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gantry_coord_v1_coord_proto_goTypes,
		DependencyIndexes: file_gantry_coord_v1_coord_proto_depIdxs,
		EnumInfos:         file_gantry_coord_v1_coord_proto_enumTypes,
		MessageInfos:      file_gantry_coord_v1_coord_proto_msgTypes,
	}.Build()
	File_gantry_coord_v1_coord_proto = out.File
	file_gantry_coord_v1_coord_proto_goTypes = nil
	file_gantry_coord_v1_coord_proto_depIdxs = nil
}
