#!/usr/bin/env bash

DEMO_INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEMO_ROOT="$(cd "${DEMO_INFRA_DIR}/.." && pwd)"
REPO_ROOT="$(cd "${DEMO_ROOT}/../.." && pwd)"

log() {
    printf '==> %s\n' "$*"
}

warn() {
    printf 'WARN: %s\n' "$*" >&2
}

die() {
    printf 'ERROR: %s\n' "$*" >&2
    exit 1
}

require_cmd() {
    local missing=0
    for cmd in "$@"; do
        if ! command -v "${cmd}" >/dev/null 2>&1; then
            printf 'missing required command: %s\n' "${cmd}" >&2
            missing=1
        fi
    done
    [[ "${missing}" == "0" ]] || exit 1
}

require_env() {
    local name
    for name in "$@"; do
        if [[ -z "${!name:-}" ]]; then
            die "${name} is required; set it in your env file"
        fi
    done
}

load_demo_env() {
    local env_file="${1:-${DEMO_INFRA_ENV:-${DEMO_INFRA_DIR}/env.local}}"
    # Snapshot externally-set sentinels so the env file cannot silently
    # override an explicit CONFIRM_DESTROY=yes from the caller.
    local _preset_confirm_destroy="${CONFIRM_DESTROY:-}"
    if [[ -n "${env_file}" ]]; then
        if [[ -f "${env_file}" ]]; then
            # shellcheck disable=SC1090
            source "${env_file}"
        elif [[ "${env_file}" != "${DEMO_INFRA_DIR}/env.local" ]]; then
            die "env file not found: ${env_file}"
        fi
    fi
    if [[ -n "${_preset_confirm_destroy}" ]]; then
        CONFIRM_DESTROY="${_preset_confirm_destroy}"
    fi

    : "${AZ_LOCATION:=canadacentral}"
    : "${AZ_RESOURCE_GROUP:=gantry-demo-rg}"
    : "${ACR_SKU:=Standard}"
    : "${AKS_NAME:=gantry-demo-aks}"
    : "${AKS_NODE_COUNT:=20}"
    : "${AKS_NODE_VM_SIZE:=Standard_D4s_v5}"
    : "${AKS_NODE_OS_DISK_GB:=128}"
    : "${AKS_NETWORK_PLUGIN:=azure}"
    : "${IMAGE_PLATFORM:=linux/amd64}"
    : "${PROXY_IMAGE_REPO:=acr-origin-proxy}"
    : "${GANTRY_IMAGE_REPO:=gantry}"
    : "${BUILD_GANTRY_IMAGE:=true}"
    : "${GANTRY_DEMO_NAMESPACE:=gantry-demo}"
    : "${MONITORING_NAMESPACE:=monitoring}"
    : "${KPS_RELEASE:=kps}"
    : "${GRAFANA_ADMIN_PASSWORD:=gantry-demo}"
    : "${CONFIRM_DESTROY:=no}"

    if [[ -z "${IMAGE_TAG:-}" ]]; then
        if IMAGE_TAG="$(cd "${REPO_ROOT}" && git describe --tags --always --dirty 2>/dev/null)"; then
            :
        else
            IMAGE_TAG="demo-$(date +%Y%m%d%H%M%S)"
        fi
    fi

    : "${PROXY_SMOKE_REPO:=${PROXY_IMAGE_REPO}}"
    : "${PROXY_SMOKE_TAG:=${IMAGE_TAG}}"

    export AZ_LOCATION AZ_RESOURCE_GROUP ACR_SKU AKS_NAME AKS_NODE_COUNT
    export AKS_NODE_VM_SIZE AKS_NODE_OS_DISK_GB AKS_NETWORK_PLUGIN IMAGE_PLATFORM
    export IMAGE_TAG PROXY_IMAGE_REPO GANTRY_IMAGE_REPO BUILD_GANTRY_IMAGE
    export GANTRY_DEMO_NAMESPACE MONITORING_NAMESPACE KPS_RELEASE
    export GRAFANA_ADMIN_PASSWORD CONFIRM_DESTROY PROXY_SMOKE_REPO PROXY_SMOKE_TAG
}

validate_acr_name() {
    require_env ACR_NAME
    if [[ ! "${ACR_NAME}" =~ ^[a-z0-9]{5,50}$ ]]; then
        die "ACR_NAME must be 5-50 lowercase alphanumeric chars, got: ${ACR_NAME}"
    fi
}

select_subscription() {
    if [[ -n "${AZ_SUBSCRIPTION:-}" ]]; then
        log "Selecting Azure subscription ${AZ_SUBSCRIPTION}"
        az account set --subscription "${AZ_SUBSCRIPTION}"
    fi
}

acr_login_server() {
    az acr show \
        --resource-group "${AZ_RESOURCE_GROUP}" \
        --name "${ACR_NAME}" \
        --query loginServer \
        -o tsv
}

acr_resource_id() {
    az acr show \
        --resource-group "${AZ_RESOURCE_GROUP}" \
        --name "${ACR_NAME}" \
        --query id \
        -o tsv
}

proxy_image() {
    printf '%s/%s:%s' "$(acr_login_server)" "${PROXY_IMAGE_REPO}" "${IMAGE_TAG}"
}

gantry_image() {
    printf '%s/%s:%s' "$(acr_login_server)" "${GANTRY_IMAGE_REPO}" "${IMAGE_TAG}"
}

write_state_file() {
    local state_file="${DEMO_INFRA_DIR}/.state.env"
    local login_server proxy gantry
    login_server="$(acr_login_server)"
    proxy="${login_server}/${PROXY_IMAGE_REPO}:${IMAGE_TAG}"
    gantry="${login_server}/${GANTRY_IMAGE_REPO}:${IMAGE_TAG}"
    cat >"${state_file}" <<EOF
# Generated by deploy/demo/infra scripts. Safe to delete and regenerate.
export AZ_RESOURCE_GROUP="${AZ_RESOURCE_GROUP}"
export AKS_NAME="${AKS_NAME}"
export ACR_NAME="${ACR_NAME}"
export ACR_LOGIN_SERVER="${login_server}"
export IMAGE_TAG="${IMAGE_TAG}"
export PROXY_IMAGE="${proxy}"
export GANTRY_IMAGE="${gantry}"
EOF
    log "Wrote ${state_file}"
}

ensure_kube_credentials() {
    log "Fetching AKS credentials for ${AKS_NAME}"
    az aks get-credentials \
        --resource-group "${AZ_RESOURCE_GROUP}" \
        --name "${AKS_NAME}" \
        --overwrite-existing
}
